Traceback (most recent call last):
  File "./daemon_test_2.py", line 26, in <module>
    Main()
  File "./daemon_test_2.py", line 23, in Main
    daemonTest.start()
  File "/home/forrest/piSense/daemons/daemon.py", line 83, in start
    self.run()
  File "./daemon_test_2.py", line 17, in run
    self.loop()
  File "./daemon_test_2.py", line 11, in loop
    with open('~/piSense/tmp/daemon/daemonWrite.txt','w') as df:
FileNotFoundError: [Errno 2] No such file or directory: '~/piSense/tmp/daemon/daemonWrite.txt'
